package com.sah.model.entities;
// Generated 11-jun-2014 0:40:44 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idcliente;
     private String nombre;
     private String apellido;
     private String ocupacion;
     private String correo;
     private String telefono;
     private String dni;
     private Date fechaNac;
     private Set reservas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idcliente, String nombre, String apellido, String ocupacion, String correo, String telefono) {
        this.idcliente = idcliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.ocupacion = ocupacion;
        this.correo = correo;
        this.telefono = telefono;
    }
    public Cliente(int idcliente, String nombre, String apellido, String ocupacion, String correo, String telefono, String dni, Set reservas,Date fechaNac) {
       this.idcliente = idcliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ocupacion = ocupacion;
       this.correo = correo;
       this.telefono = telefono;
       this.dni = dni;
       this.reservas = reservas;
       this.fechaNac = fechaNac;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

    public Date getFechaNac() {
        return fechaNac;
    }

    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }




}


