package com.sah.model.entities;
// Generated 11-jun-2014 0:40:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cuarto generated by hbm2java
 */
public class Cuarto  implements java.io.Serializable {


        private int idcuarto;
        private Ubicacion ubicacion;
        private Arrendatario arrendatario;
        private String caracteristicas;
        private String banio;
        private String restricciones;
        private String estado;
        private String detalleUbicacion;
        private String direccion;
        private String telefonoContacto;
        private Set detalles = new HashSet(0);
        private Set reservas = new HashSet(0);

    public Cuarto() {
    }

	
    public Cuarto(int idcuarto, String caracteristicas, String banio, String restricciones, String estado, String detalleUbicacion,String direccion,String telefonoContacto) {
        this.idcuarto = idcuarto;
        this.caracteristicas = caracteristicas;
        this.banio = banio;
        this.restricciones = restricciones;
        this.estado = estado;
        this.detalleUbicacion = detalleUbicacion;
        this.direccion = direccion;
        this.telefonoContacto = telefonoContacto;
    }
    public Cuarto(int idcuarto, Ubicacion ubicacion, Arrendatario arrendatario, String caracteristicas,String detalleUbicacion, String banio, String restricciones, String estado,String direccion, String telefonoContacto, Set detalles, Set reservas) {
       this.idcuarto = idcuarto;
       this.ubicacion = ubicacion;
       this.arrendatario = arrendatario;
       this.caracteristicas = caracteristicas;
       this.banio = banio;
       this.restricciones = restricciones;
       this.estado = estado;
       this.detalleUbicacion = detalleUbicacion;
       this.direccion = direccion;
       this.telefonoContacto = telefonoContacto;
       this.detalles = detalles;
       this.reservas = reservas;
    }
   
    public int getIdcuarto() {
        return this.idcuarto;
    }
    
    public void setIdcuarto(int idcuarto) {
        this.idcuarto = idcuarto;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Arrendatario getArrendatario() {
        return this.arrendatario;
    }
    
    public void setArrendatario(Arrendatario arrendatario) {
        this.arrendatario = arrendatario;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public String getBanio() {
        return this.banio;
    }
    
    public void setBanio(String banio) {
        this.banio = banio;
    }
    public String getRestricciones() {
        return this.restricciones;
    }
    
    public void setRestricciones(String restricciones) {
        this.restricciones = restricciones;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
       public String getDetalleUbicacion() {
        return this.detalleUbicacion;
    }
    
    public void setDetalleUbicacion(String detalleUbicacion) {
        this.detalleUbicacion = detalleUbicacion;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getTelefonoContacto() {
        return telefonoContacto;
    }

    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }




}


