package com.sah.model.entities;
// Generated 11-jun-2014 0:40:44 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private int idreserva;
     private Cuarto cuarto;
     private Cliente cliente;
     private String fecha;
     private String tiempo;
     private String monto;
     private Integer idArrendatario;
     private Set comentarioses = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(int idreserva, String fecha, String tiempo, String monto) {
        this.idreserva = idreserva;
        this.fecha = fecha;
        this.tiempo = tiempo;
        this.monto = monto;
    }
    public Reserva(int idreserva, Cuarto cuarto, Cliente cliente, String fecha, String tiempo, String monto, Integer idArrendatario, Set comentarioses) {
       this.idreserva = idreserva;
       this.cuarto = cuarto;
       this.cliente = cliente;
       this.fecha = fecha;
       this.tiempo = tiempo;
       this.monto = monto;
       this.idArrendatario = idArrendatario;
       this.comentarioses = comentarioses;
    }
   
    public int getIdreserva() {
        return this.idreserva;
    }
    
    public void setIdreserva(int idreserva) {
        this.idreserva = idreserva;
    }
    public Cuarto getCuarto() {
        return this.cuarto;
    }
    
    public void setCuarto(Cuarto cuarto) {
        this.cuarto = cuarto;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }
    public Integer getIdArrendatario() {
        return this.idArrendatario;
    }
    
    public void setIdArrendatario(Integer idArrendatario) {
        this.idArrendatario = idArrendatario;
    }
    public Set getComentarioses() {
        return this.comentarioses;
    }
    
    public void setComentarioses(Set comentarioses) {
        this.comentarioses = comentarioses;
    }




}


